apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '70'
spec:
  project: default
  source:
    repoURL: git@github.com:kubefirst-dos-mlk/gitops.git
    path: registry/clusters/installer/components/kubefirst
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
